export const NOTIFICATIONS = {
  NOTIFICATION_ORDER_UPDATED: 'NOTIFICATION_ORDER_UPDATED',
  NOTIFICATION_ORDER_CREATED: 'NOTIFICATION_ORDER_CREATED',
  NOTIFICATION_REQUEST_CONTACT: 'NOTIFICATION_REQUEST_CONTACT',
  NOTIFICATION_NEW_BID: 'NOTIFICATION_NEW_BID',
  NOTIFICATION_NEW_MESSAGE: 'NOTIFICATION_NEW_MESSAGE',
  NOTIFICATION_EXPIRED_AUCTION: 'NOTIFICATION_EXPIRED_AUCTION'
};
