const routes = {
  InitialLoading: 'InitialLoading',
  Login: 'Login',
  Home: 'Home',
  SignUp: 'SignUp',
  Points: 'Points',
  Orders: 'Orders',
  ActiveOrders: 'ActiveOrders',
  PastOrders: 'PastOrders',
  Profile: 'Profile',
  RecoverPassword: 'RecoverPassword',
  ScannerQR: 'ScannerQR',
  Configuration: 'Configuration',
  ChooseConfiguration: 'ChooseConfiguration',
  ExpiredAuctions: 'ExpiredAuctions',
  Auctions: 'Auctions',
  ActiveAuctions: 'ActiveAuctions',
  HomeMenu: 'HomeMenu',
  Chats: 'Chats',
  SupplierChat: 'SupplierChat',
  CreateOrder: 'CreateOrder',
  CreateAuction: 'CreateAuction',
  OrderDetail: 'OrderDetail',
  AuctionDetail: 'AuctionDetail',
  Search: 'Search',
  ProductDetail: 'ProductDetail',
  SupplierProfile: 'SupplierProfile',
  ClosedAuctions: 'ClosedAuctions',
  Bids: 'Bids',
  AgendaRequest: 'AgendaRequest'
};

export default routes;
